from typing import Any, Optional, Union, overload, TypeVar

from .containers import TList
from . import RDF

RObject = TypeVar('RObject', bound=TObject)


class TObject:
    def ClassName(self) -> str:
        """
        Return the name of the class.
        """
        ...
    
    def Draw(self, option: str = "") -> None:
        """
        Default Draw method for all objects.
        """
        ...
    def GetTitle(self) -> str:
        """
        Returns title of object.

        This default method returns the class title (i.e. description).
        Classes that give objects a title should override this method. 
        """
        ...
    def SaveAs(self, filename: str, option: str = "") -> None:
        """
        Save this object in the file specified by filename.

            - if `filename` contains `.root` the object is saved in filename as root binary file.
            - if `filename` contains `.xml` the object is saved in filename as a xml ascii file.
            - if `filename` contains `.cc` the object is saved in filename as C code independant
              from ROOT. The code is generated via `SavePrimitive()`. Specific code should be implemented
              in each object to handle this option. Like in `TF1.SavePrimitive()`.

        otherwise the object is written to filename as a CINT/C++ script. The C++ code to rebuild
        this object is generated via `SavePrimitive()`. The "option" parameter is passed to `SavePrimitive`.
        By default it is an empty string. It can be used to specify the `Draw` option in the code generated by
        `SavePrimitive`.

        The function is available via the object context menu.
        """
        ...
    @overload    
    def FindObject(self, name: str) -> Optional['TObject']:
        """
        Must be redefined in derived classes.

        This function is typically used with TCollections,
        but can also be used to find an object by name inside this object. 
        
        Parameters
        ----------
        name : str
            The name of the object to find.
        
        Returns
        -------
        TObject | None
            The found object or None if not found.
        """
        ...
    @overload
    def FindObject(self, obj : RObject) -> RObject:
        """
        Must be redefined in derived classes.

        This function is typically used with TCollections,
        but can also be used to find an object by name inside this object. 
        
        Parameters
        ----------
        obj : TObject
            The type of the object to find.
        
        Returns
        -------
        TObject | None
            Object with the same type as the one provided.
        """
        ...

class TAttLine:
    @overload
    def SetLineColor(self, color: int):
        """
        Set the line color.
        """
        ...
    @overload
    def SetLineColor(self, color: 'TColorNumber'):
        """
        Set the line color using a TColorNumber.
        """
        ...
    def SetLineColorAlpha(self, color: int, alpha: float) -> None:
        """
        Set the line color with transparency.
        
        Parameters
        ----------
        color : int
            The color to set.
        alpha : float
            The transparency level (0.0 to 1.0).
        """
        ...

class TAttFill:
    def SetFillStyle(self, style : int) -> None:
        """
        Set the fill area style.
        
        Conventions for fill styles
        ----------------------------
        `0` : hollow
        `1001` : Solid
        `3000+pattern_number` (see below)
        
        For `TPad` only:
            `4000` :the window is transparent.

            `4000` to `4100` the window is 100% transparent to 100% opaque.

            The pad transparency is visible in binary outputs files like gif, jpg, png etc ..
            but not in vector graphics output files like PS, PDF and SVG. This convention
            (fill style > 4000) is kept for backward compatibility. It is better to use the color
            transparency instead.

        pattern_number can have any value from 1 to 25 (see table), or any value from 100 to 999. 
        For the latest the numbering convention is the following:
        ```
        pattern_number = ijk      (FillStyle = 3ijk)
 
        i (1-9) : specify the space between each hatch
                1 = 1/2mm  9 = 6mm
        
        j (0-9) : specify angle between 0 and 90 degrees
                0 = 0
                1 = 10
                2 = 20
                3 = 30
                4 = 45
                5 = Not drawn
                6 = 60
                7 = 70
                8 = 80
                9 = 90
        
        k (0-9) : specify angle between 90 and 180 degrees
                0 = 180
                1 = 170
                2 = 160
                3 = 150
                4 = 135
                5 = Not drawn
                6 = 120
                7 = 110
                8 = 100
                9 = 90
        ```
        """
        ...
    @overload
    def SetFillColor(self, color: int) -> None:
        """
        Set the fill area color.

        Parameters
        ----------
        color : int
            The color to set.
        """
        ...
    @overload
    def SetFillColor(self, color: 'TColorNumber') -> None:
        """
        Set the fill area color using a TColorNumber.

        Parameters
        ----------
        color : TColorNumber
            The color to set.
        """
        ...
    def SetFillColorAlpha(self, fcolor: Union[int, 'TColorNumber'], falpha: float) -> None:
        """
        Set a transparent fill color.
        
        Parameters
        ----------
        fcolor : int | TColorNumber
            Defines the fill color.
        falpha : float
            Defines the percentage of opacity from 0. (fully transparent) to 1. (fully opaque). 
        """
        ...
class TVirtualPad(TObject, TAttFill):
    def GetListOfPrimitives(self) -> 'TList[TVirtualPad]':
        """
        Return the list of primitives in this pad.
        
        The list of primitives is a `TList` containing all objects drawn in this pad.
        """
        ...


class TNamed(TObject):
    def GetName(self) -> str:
        """
        Return the name of the object.
        """
        ...


class TNamed(TObject):
    def GetName(self) -> str:
        """
        Return the name of the object.
        
        This default method returns the class name. Classes that give objects a name should override this method. 
        """
        ...
    def SetName(self, name: str) -> None:
        """
        Set the name of the TNamed.

        WARNING: if the object is a member of a THashTable or THashList
        container the container must be Rehash()'ed after SetName(). For
        example the list of objects in the current directory is a THashList.
        """
        ...
    def SetTitle(self, title: str) -> None:
        """
        Set the title of the object.
        """
        ...
class TAttAxis:
    pass

class TAttLine:
    @overload
    def SetLineColor(self, color: int) -> None:
        """
        Set the line color.
        
        Parameters
        ----------
        color : int
            The color to set.
        """
        ...
    @overload
    def SetLineColor(self, color: 'TColorNumber') -> None:
        """
        Set the line color using a TColorNumber.
        
        Parameters
        ----------
        color : TColorNumber
            The color to set.
        """
        ...
    def SetLineColorAlpha(self, color: Union[int, 'TColorNumber'], alpha: float) -> None:
        """
        Set the line color with transparency.
        """
        ...
    def SetLineWidth(self, width: int) -> None:
        """
        Set the line width.
        
        Parameters
        ----------
        width : int
            The width of the line in pixels.
        """
        ...
    def SetLineStyle(self, style: int) -> None:
        """
        Set the line style.
        
        Parameters
        ----------
        style : int
            The line style to set. Common styles are:
            - 1: solid
            - 2: dashed
            - 3: dotted
            - 4: dash-dot
            - 5: long dash-dot
            - 6: dash-dot-dot-dot
            - 7: long dash
            - 8: dash-dot-dot
            - 9: longer dash
            - 10: long dash-dot
        """
        ...
    def SetLineStyleString(self, i : int, text : str) -> None:
        """
        Set the line style string.
        
        Parameters
        ----------
        i : int
            The index of the line style to set.
        text : str
            The string representation of the line style.
            The string defines the dash length and the gap length. For example:
            - 1 (solid): ""
            - 2 (dashed): "12 12"
            - 3 (dotted): "4 8"
            - 4 (dash-dot): "12 16 4 16"
            - 5 (long dash-dot): "20 12 4 12"
            - 6 (dash-dot-dot-dot): "20 12 4 12 4 12 4 12"
            - 7 (long dash): "20 20"
            - 8 (dash-dot-dot): "20 12 4 12 4 12"
            - 9 (longer dash): "80 20"

        Notes
        -----
        - Up to 30 different styles may be defined.
        - The opening and closing brackets may be omitted
        - It is recommended to use 4 as the smallest segment length and multiple of 4 for other lengths.
        - The line style 1 to 10 are predefined. 1 to 4 cannot be changed.

        """
        ...
class TAttMarker:
    @overload
    def SetMarkerColor(self, color: int = 1) -> None:
        """
        Set the marker color.
        
        Parameters
        ----------
        color : int
            The color to set.
        """
        ...
    @overload
    def SetMarkerColor(self, color: 'TColorNumber') -> None:
        """
        Set the marker color using a TColorNumber.
        
        Parameters
        ----------
        color : TColorNumber
            The color to set.
        """
        ...
    def SetMarkerColorAlpha(self, mcolor: Union[int, 'TColorNumber'], malpha: float) -> None:
        """
        Set a transparent marker color.
        
        Parameters
        ----------
        mcolor : int | TColorNumber
            Defines the marker color.
        malpha : float
            Defines the percentage of opacity from 0. (fully transparent) to 1. (fully opaque). 
        """
        ...

class TColorNumber(TNamed):
    pass


class TColor(TNamed):
    """
    The color creation and management class.
    """
    @overload
    def __init__(self, color: int, r: float, g: float, b: float, name :str = "", a :float = 1) -> None:
        """
        Normal color constructor.

        Initialize a color structure. Compute the RGB and HLS color components.
        The color title is set to its hexadecimal value. 
        
        Parameters
        ----------
        number : int
            The color number.
        r : float
            Red component (0.0 to 1.0).
        g : float
            Green component (0.0 to 1.0).
        b : float
            Blue component (0.0 to 1.0).
        name : str, optional
            The name of the color. Defaults to an empty string.
        a : float, optional
            Alpha transparency (default is 1.0, fully opaque).
        """
        ...
    @overload
    def __init__(self, r : float, g : float, b : float, a : float = 1) -> None:
        """
        Fast TColor constructor.

        It creates a color with an index just above the current highest one.
        It does not name the color. This is useful to create palettes.
        
        Parameters
        ----------
        r : float
            Red component (0.0 to 1.0).
        g : float
            Green component (0.0 to 1.0).
        b : float
            Blue component (0.0 to 1.0).
        a : float, optional
            Alpha transparency (default is 1.0, fully opaque).
        """
    @overload
    def __init__(self, color: 'TColor') -> None:
        """
        Color copy constructor.
        """
        ...
    @staticmethod
    def GetFreeColorIndex() -> int:
        """
        Returns the free color index greater than
        the highest defined color index.

        All the color indices after this index are also free.
        It can be used to define a user custom color.
        """
        ...
    @overload
    @staticmethod
    def GetColor(color: str) -> 'TColorNumber':
        """
        Static method returning color number for color specified by hex
        color string of form: "#rrggbb", where rr, gg and bb are in hex between [0,FF], e.g.

        "#c0c0c0". Also alpha channel is applied when hex string includes fourth number e.g "#c0c0c0ff"

        The color retrieval is done using a threshold defined by SetColorThreshold.

        If specified color does not exist it will be created with as name "#rrggbb" with rr,
        gg and bb in hex between [0,FF]. 
        """
        ...
    @overload
    @staticmethod
    def GetColor(r : float, g : float, b : float, a : float = 1) -> 'TColorNumber':
        """
        Static method returning color number for color specified by r, g and b.

        The r,g,b should be in the range [0,1].

        The color retrieval is done using a threshold defined by SetColorThreshold.

        If specified color does not exist it will be created with as name "#rrggbb"
        with rr, gg and bb in hex between [0,FF].
        """
        ...
    @overload
    @staticmethod
    def GetColor(r : int, g : int, b : int, a : float = 1) -> 'TColorNumber':
        """
        Static method returning color number for color specified by r, g and b.

        The r,g,b should be in the range [0,255].

        The color retrieval is done using a threshold defined by SetColorThreshold.

        If specified color does not exist it will be created with as name "#rrggbb"
        with rr, gg and bb in hex between [0,FF].
        """
        ...
    
    def SetPalette(self, ncolors : int, colors : int, alpha : float = 1) -> None:
        """
        The color palette is used by the histogram classes (see TH1.Draw options).
        For example TH1.Draw("col") draws a 2-D histogram with cells represented by a box
        filled with a color CI function of the cell content. if the cell content is N, the
        color CI used will be the color number in colors[N],etc. If the maximum cell content
        is > ncolors, all cell contents are scaled to ncolors.

        if ncolors <= 0 a default palette (see below) of 50 colors is defined. The colors
        defined in this palette are OK for coloring pads, labels.
        ```
        index 0->9   : grey colors from light to dark grey
        index 10->19 : "brown" colors
        index 20->29 : "blueish" colors
        index 30->39 : "redish" colors
        index 40->49 : basic colors
        ```

        if `ncolors == 1 & colors == 0`, a Rainbow Color map is created with 50 colors. It
        is kept for backward compatibility. Better palettes like `kBird` are recommended.

        High quality predefined palettes with 255 colors are available when `colors == 0`.
        The following value of ncolors give access to:
        ```
        if ncolors = 51 and colors=0, a Deep Sea palette is used.
        if ncolors = 52 and colors=0, a Grey Scale palette is used.
        if ncolors = 53 and colors=0, a Dark Body Radiator palette is used.
        if ncolors = 54 and colors=0, a Two-Color Hue palette is used.(dark blue through neutral gray to bright yellow)
        if ncolors = 55 and colors=0, a Rain Bow palette is used.
        if ncolors = 56 and colors=0, an Inverted Dark Body Radiator palette is used.
        if ncolors = 57 and colors=0, a monotonically increasing L value palette is used.
        if ncolors = 58 and colors=0, a Cubehelix palette is used
                                        (Cf. Dave Green's "cubehelix" colour scheme at http://www.mrao.cam.ac.uk/~dag/CUBEHELIX/)
        if ncolors = 59 and colors=0, a Green Red Violet palette is used.
        if ncolors = 60 and colors=0, a Blue Red Yellow palette is used.
        if ncolors = 61 and colors=0, an Ocean palette is used.
        if ncolors = 62 and colors=0, a Color Printable On Grey palette is used.
        if ncolors = 63 and colors=0, an Alpine palette is used.
        if ncolors = 64 and colors=0, an Aquamarine palette is used.
        if ncolors = 65 and colors=0, an Army palette is used.
        if ncolors = 66 and colors=0, an Atlantic palette is used.
        if ncolors = 67 and colors=0, an Aurora palette is used.
        if ncolors = 68 and colors=0, an Avocado palette is used.
        if ncolors = 69 and colors=0, a Beach palette is used.
        if ncolors = 70 and colors=0, a Black Body palette is used.
        if ncolors = 71 and colors=0, a Blue Green Yellow palette is used.
        if ncolors = 72 and colors=0, a Brown Cyan palette is used.
        if ncolors = 73 and colors=0, a CMYK palette is used.
        if ncolors = 74 and colors=0, a Candy palette is used.
        if ncolors = 75 and colors=0, a Cherry palette is used.
        if ncolors = 76 and colors=0, a Coffee palette is used.
        if ncolors = 77 and colors=0, a Dark Rain Bow palette is used.
        if ncolors = 78 and colors=0, a Dark Terrain palette is used.
        if ncolors = 79 and colors=0, a Fall palette is used.
        if ncolors = 80 and colors=0, a Fruit Punch palette is used.
        if ncolors = 81 and colors=0, a Fuchsia palette is used.
        if ncolors = 82 and colors=0, a Grey Yellow palette is used.
        if ncolors = 83 and colors=0, a Green Brown Terrain palette is used.
        if ncolors = 84 and colors=0, a Green Pink palette is used.
        if ncolors = 85 and colors=0, an Island palette is used.
        if ncolors = 86 and colors=0, a Lake palette is used.
        if ncolors = 87 and colors=0, a Light Temperature palette is used.
        if ncolors = 88 and colors=0, a Light Terrain palette is used.
        if ncolors = 89 and colors=0, a Mint palette is used.
        if ncolors = 90 and colors=0, a Neon palette is used.
        if ncolors = 91 and colors=0, a Pastel palette is used.
        if ncolors = 92 and colors=0, a Pearl palette is used.
        if ncolors = 93 and colors=0, a Pigeon palette is used.
        if ncolors = 94 and colors=0, a Plum palette is used.
        if ncolors = 95 and colors=0, a Red Blue palette is used.
        if ncolors = 96 and colors=0, a Rose palette is used.
        if ncolors = 97 and colors=0, a Rust palette is used.
        if ncolors = 98 and colors=0, a Sandy Terrain palette is used.
        if ncolors = 99 and colors=0, a Sienna palette is used.
        if ncolors = 100 and colors=0, a Solar palette is used.
        if ncolors = 101 and colors=0, a South West palette is used.
        if ncolors = 102 and colors=0, a Starry Night palette is used.
        if ncolors = 103 and colors=0, a Sunset palette is used.
        if ncolors = 104 and colors=0, a Temperature Map palette is used.
        if ncolors = 105 and colors=0, a Thermometer palette is used.
        if ncolors = 106 and colors=0, a Valentine palette is used.
        if ncolors = 107 and colors=0, a Visible Spectrum palette is used.
        if ncolors = 108 and colors=0, a Water Melon palette is used.
        if ncolors = 109 and colors=0, a Cool palette is used.
        if ncolors = 110 and colors=0, a Copper palette is used.
        if ncolors = 111 and colors=0, a Gist Earth palette is used.
        if ncolors = 112 and colors=0, a Viridis palette is used.
        if ncolors = 113 and colors=0, a Cividis palette is used.
        ```
        These palettes can also be accessed by names:
        ```
        kDeepSea=51,          kGreyScale=52,    kDarkBodyRadiator=53,
        kBlueYellow= 54,      kRainBow=55,      kInvertedDarkBodyRadiator=56,
        kBird=57,             kCubehelix=58,    kGreenRedViolet=59,
        kBlueRedYellow=60,    kOcean=61,        kColorPrintableOnGrey=62,
        kAlpine=63,           kAquamarine=64,   kArmy=65,
        kAtlantic=66,         kAurora=67,       kAvocado=68,
        kBeach=69,            kBlackBody=70,    kBlueGreenYellow=71,
        kBrownCyan=72,        kCMYK=73,         kCandy=74,
        kCherry=75,           kCoffee=76,       kDarkRainBow=77,
        kDarkTerrain=78,      kFall=79,         kFruitPunch=80,
        kFuchsia=81,          kGreyYellow=82,   kGreenBrownTerrain=83,
        kGreenPink=84,        kIsland=85,       kLake=86,
        kLightTemperature=87, kLightTerrain=88, kMint=89,
        kNeon=90,             kPastel=91,       kPearl=92,
        kPigeon=93,           kPlum=94,         kRedBlue=95,
        kRose=96,             kRust=97,         kSandyTerrain=98,
        kSienna=99,           kSolar=100,       kSouthWest=101,
        kStarryNight=102,     kSunset=103,      kTemperatureMap=104,
        kThermometer=105,     kValentine=106,   kVisibleSpectrum=107,
        kWaterMelon=108,      kCool=109,        kCopper=110,
        kGistEarth=111        kViridis=112,     kCividis=113
        ```
        
        For example:
        ```
        ROOT.gStyle.SetPalette(ROOT.kBird);
        ```
        Set the current palette as "Bird" (number 57).

        The color numbers specified in the palette can be viewed by selecting the
        item "colors" in the "VIEW" menu of the canvas toolbar. The color parameters can
        be changed via TColor.SetRGB.

        Note that when drawing a 2D histogram h2 with the option "COL" or "COLZ" or with
        any "CONT" options using the color map, the number of colors used is defined by the
        number of contours n specified with: `h2.SetContour(n)`
        """
        pass