from typing import Any

from .core import TNamed
from .tree import TTree

class TDirectory(TNamed):
    pass

class TDirectoryFile(TDirectory):
    pass

class TFile(TDirectoryFile):
    def __init__(self, name: str, option: str = "READ") -> None: ...
    def Get(self, name: str) -> Any | TTree: ...
    def Close(self) -> None: ...
    def Write(self) -> int: ...
    def __enter__(self) -> 'TFile': ...
    def __exit__(self, *args: Any) -> None: ...
