from typing import Any

from .core import TNamed, TAttFill

class TTree(TNamed, TAttFill()):
    def __init__(self, name: str, title: str) -> None: ...
    def Branch(self, name: str, obj: Any, leaflist: str = "") -> Any: ...
    def Fill(self) -> int: ...
    def GetEntries(self) -> int: ...
    def Draw(self, varexp: str, selection: str = "", option: str = "") -> int: ...
